name: nurahelp
description: "Cross Platform Mobile App for NuraHelp"


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  get: ^4.7.2
  google_nav_bar: ^5.0.7
  iconify_flutter_plus: ^1.0.4
  material_symbols_icons: ^4.2815.1
  intl: ^0.20.2
  fl_chart: ^1.0.0
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #
  fonts:
     - family: Poppins-Bold
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Bold.ttf
     - family: Poppins-SemiBold
       fonts:
         - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
     - family: Poppins-Medium
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Medium.ttf
     - family: Poppins-Regular
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Regular.ttf
     - family: Poppins-Light
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Light.ttf
     - family: Poppins-ExtraLight
       fonts:
         - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
     - family: Poppins-Thin
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Thin.ttf