name: nurahelp
description: "Cross Platform Mobile App for NuraHelp"


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_nav_bar: ^5.0.7
  material_symbols_icons: ^4.2815.1
  intl: ^0.19.0
  connectivity_plus: ^6.1.4
  fl_chart: ^1.0.0
  autoscale_tabbarview: ^1.0.2
  pin_code_fields: ^8.0.1
  flutter_rating_stars: ^1.1.0
  syncfusion_flutter_sliders: ^30.1.41
  syncfusion_flutter_core: ^30.1.41
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  iconify_flutter_plus: ^1.0.4
  http: ^1.5.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.6
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.4
#  zego_uikit_prebuilt_call: ^4.18.0
#  zego_uikit_signaling_plugin: ^2.8.16
#  shelf_web_socket: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo/NuraAndroidLogo.png" # Fallback for older iOS
    adaptive_icon_background: "#3471eb"
    adaptive_icon_foreground: "assets/logo/NuraAndroidLogo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/NuraIOSLogo.png
  color_dark: "#3471eb"
  image_dark: assets/logo/NuraIOSLogoAlt.png
  branding: assets/logo/brandDark.png
  branding_dark: assets/logo/brand.png

  branding_mode: bottom
  branding_bottom_padding: 48
  # --- Android 12+ Support (Mandatory for 2026) ---
  android_12:
    branding: assets/logo/brandDark.png
    branding_dark: assets/logo/brand.png
    image: assets/logo/NuraAndroidLogo.png
    image_dark: assets/logo/NuraAndroidLogoAlt.png
    color: "#ffffff"
    color_dark: "#3471eb"

  android: true
  ios: true
  web: false



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/nura_icons/
    - assets/animations/
    - assets/logo/
    - assets/images/


  #
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    - family: NuraIcons
      fonts:
        - asset: assets/fonts/NuraIcons.ttf